version = 1

exclude_patterns = ["/EasyBot.py, /EasyBot-Plugins, /DisQuest, /Bot/Cogs/disquest.py"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "yapf"
enabled = true