default_language_version:
    python: python3.11
files: '.py'
exclude: ".env,.yml,.gitignore,.git,.md,.txt"
default_stages: [push, commit]
repos:
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -  id: bandit
       args: ["-c", "pyproject.toml"]
       name: Bandit
       stages: [commit]
       additional_dependencies: ["bandit[toml]"]
        
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        name: Black
        stages: [commit]
        
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--recursive"]
        name: AutoFlake
        description: "Format with AutoFlake"
        stages: [commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        name: Ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--config", "pyproject.toml"]
        
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: ISort
        description: "Format with Isort"
        stages: [commit]


