version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install --upgrade -r docs/requirements.txt
    - python -m sphinx -aEnTW --builder html --keep-going docs/ $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true