ignore:
  - "Bot/Libs/ui/**"
  - "Bot/Libs/utils/pages/**"
  - "Bot/Libs/utils/kumiko_logger.py"
  - "Bot/Libs/utils/embeds.py"
  - "Bot/Libs/utils/member_utils.py" # Untestable code. Even when running dpytest, the coro requires the bot to have the guilds chunked, which is not possible using pytest
  - "Bot/Libs/utils/prefix.py" # This contains an coroutine that we can't even test to begin with
  - "Bot/Libs/cog_utils/pins/pin_utils.py" # Contains untestable code.
  - "Bot/Cogs/**" # There are just too much code to test here
  - "Bot/Libs/utils/checks.py" # Contains untestable code, but may be tested later
  - "Bot/Libs/utils/time.py" # too lazy to test
  - "Bot/Libs/utils/message_constants.py" # Literally just constants so there is no need to test
  - "Bot/Libs/utils/timer/**" # nah
  - "Bot/Libs/utils/pg_init_codecs.py" # dont think u can test this...
  - "Bot/Libs/errors/utils.py" # Technically you can test this but i'm too lazy
  - "Bot/Libs/config/**"
  - "Bot/Libs/utils/webhooks.py" # Probably can be tested but eh
  - "Bot/Libs/utils/context.py" # Impossible to unit test and mock
  - "Bot/Libs/utils/help.py"
  - "Bot/Libs/utils/modal.py"
  - "Bot/Libs/utils/view.py"
  - "Bot/Libs/utils/transport.py"
  - "Bot/Libs/utils/tree.py"