ignore:
  - "Bot/Libs/ui/**"
  - "Bot/Libs/utils/help/**"
  - "Bot/Libs/utils/pages/**"
  - "Bot/Libs/utils/kumiko_logger.py"
  - "Bot/Libs/utils/embeds.py"
  - "Bot/Libs/utils/prefix.py" # This contains an coroutine that we can't even test to begin with
  - "Bot/Libs/cog_utils/pins/pin_utils.py" # Contains untestable code.