version: "3.9"
services:
  rin:
    container_name: Rin
    restart: always
    image: no767/rin-prod:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 3
        window: 120s
      mode: replicated
    env_file:
      - .env-docker-example # Rename this to .env