version: "3.9"
services:
  postgres:
    container_name: Kumiko-Postgres-Dev
    image: no767/kumiko-postgres:edge
    env_file:
      - .env
    volumes:
      - dev_postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Kumiko-Redis-Stack-Dev
    image: redis/redis-stack:7.0.6-RC5
    ports:
      - 6379:6379
    volumes:
      - dev_redis_volume:/data
    command: redis-stack-server --protected-mode no

volumes:
  dev_postgres_volume:
  dev_redis_volume:
