name: "kumiko-dev"
services:
  postgres:
    container_name: Kumiko-Postgres-Dev
    image: kumiko-pg:dev-latest
    build:
        context: ./docker/pg
        dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_volume: