version: "3.9"
name: "kumiko-staging"
services:
  postgres:
    container_name: Kumiko-Postgres
    image: kumiko-postgres:prod-latest
    build:
      context: ./Docker/pg
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - staging_postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Kumiko-Redis
    image: redis/redis-stack-server:7.2.0-v0
    ports:
      - 6379:6379
    volumes:
      - staging_redis_volume:/data
    command: redis-stack-server --save 60 1

volumes:
  staging_postgres_volume:
  staging_redis_volume:
