version: "3.9"
name: "kumiko-prod"
services:
  postgres:
    container_name: Kumiko-Postgres
    image: kumiko-postgres:prod-latest
    build:
      context: ./Docker/pg
      dockerfile: ./Docker/pg/Dockerfile
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Kumiko-Redis
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  kumiko:
    container_name: Kumiko
    image: no767/kumiko:latest
    command: sh -c '/Kumiko/wait-for postgres:5432 -- echo "[Wait-for] PostgreSQL is fully up. Waiting for Redis" && /Kumiko/wait-for redis:6379 -- echo "[Wait-for] Both PostgreSQL and Redis are fully ready. Starting up Kumiko" && /Kumiko/start.sh'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_volume: