version: "3.9"
services:
  postgres:
    container_name: Kumiko-Postgres
    image: no767/kumiko-postgres:edge
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Kumiko-Redis-Stack
    image: redis/redis-stack:7.0.6-RC6
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    command: redis-stack-server --protected-mode no

  kumiko:
    container_name: Kumiko
    image: no767/kumiko:edge
    command: sh -c '/Kumiko/wait-for postgres:5432 -- echo "[Wait-for] PostgreSQL is fully up. Waiting for Redis" && /Kumiko/wait-for redis:6379 -- echo "[Wait-for] Both PostgreSQL and Redis are fully ready. Starting up Kumiko" && /Kumiko/start.sh'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_volume:
  redis_volume:
