version: '3'

tasks:
  dev-up:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml up -d

  dev-stop:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml stop

  bot:
    preconditions:
      - test -f bot/config.yml
    cmds:
      - python3 bot/launcher.py
    silent: true
  
  check:
    cmds:
      - pyright bot
      - ruff check bot --fix --exit-non-zero-on-fix --config pyproject.toml
    silent: true

  ruff:
    cmds:
      - ruff check bot --fix ----exit-non-zero-on-fix --config pyproject.toml
      - ruff format bot --config pyproject.toml
    silent: true