name: Docker

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  Build-and-Push:
    runs-on: ubuntu-24.04

    # We want to filter out dependabot automated pushes to main
    if: ${{ github.actor != 'dependabot[bot]'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/no767/kumiko
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=main

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: no767
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/no767/kumiko-build-cache:bot
          cache-to: type=registry,mode=max,ref=ghcr.io/no767/kumiko-build-cache:bot
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}