name: Docker Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - dev
    tags:
      - 'v*'


jobs:
  Build-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/no767/kumiko
          tags: |
            type=semver,pattern={{raw}},suffix=-bullseye
            type=semver,pattern={{version}},suffix=-bullseye
            type=semver,pattern={{major}}.{{minor}},suffix=-bullseye
            type=semver,pattern={{major}},suffix=-bullseye
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev
            type=edge,branch=dev,suffix=-bullseye

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.2.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-debian-ghcr-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-debian-ghcr-
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Docker/Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-debian-ghcr

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-debian-ghcr /tmp/.buildx-cache

          
  Build-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/kumiko
          tags: |
            type=semver,pattern={{raw}},suffix=-bullseye
            type=semver,pattern={{version}},suffix=-bullseye
            type=semver,pattern={{major}}.{{minor}},suffix=-bullseye
            type=semver,pattern={{major}},suffix=-bullseye
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev
            type=edge,branch=dev,suffix=-bullseye

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.2.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-debian-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-debian-hub-

      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Docker/Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-debian-hub

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-debian-hub /tmp/.buildx-cache

  Build-Kumiko-Postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            no767/kumiko-postgres
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.2.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-kumiko-postgres-hub-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-kumiko-postgres-hub-

      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Docker/Postgres-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-kumiko-postgres

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-kumiko-postgres /tmp/.buildx-cache
