name: Docker Build (GHCR)

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - dev
    tags:
      - 'v*'


jobs:
  Build-Alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/no767/rin
          tags: |
            type=semver,pattern={{raw}},suffix=-alpine
            type=semver,pattern={{version}},suffix=-alpine
            type=semver,pattern={{major}}.{{minor}},suffix=-alpine
            type=semver,pattern={{major}},suffix=-alpine
            type=edge,branch=dev,suffix=-alpine

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-ghcr-alpine-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-ghcr-alpine-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Alpine-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-ghcr-alpine

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-ghcr-alpine /tmp/.buildx-cache

  Build-Debain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/no767/rin
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{raw}},suffix=-bullseye
            type=semver,pattern={{version}},suffix=-bullseye
            type=semver,pattern={{major}}.{{minor}},suffix=-bullseye
            type=semver,pattern={{major}},suffix=-bullseye
            type=edge,branch=dev,suffix=-bullseye
            type=edge,branch=dev

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-ghcr-debian-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-ghcr-debian-

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Debian-Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-ghcr-debian

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-ghcr-debian /tmp/.buildx-cache
