name: Format
on:
  push:
    branches:
      - dev

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.10.2
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.2
    - name: Upgrade Pip and Install Pipenv
      run: |
        pip install --upgrade pip pipenv
    - name: Cache Pipenv
      id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-v3-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install Pipenv Dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev
    - name: Format with Black
      run: |
        pipenv run black Bot/Cogs
    - name: Format with Isort
      run: |
        pipenv run isort Bot/Cogs
    - name: Format with AutoFlake
      run: |
        pipenv run autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive Bot/Cogs
    - name: Format with AutoPEP8
      run: |
        pipenv run autopep8 -r --in-place Bot/Cogs
    - name: Commit And Push All Changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Format All Cogs'
        add: 'Bot/Cogs --force --all'
        push: true
        pull: '--no-rebase'
